Hue_low : 50 
Hue_high : 102 
Saturation_low : 52 
Saturation_high : 255 
Value_low : 154 
Value_high : 255 
Area_min : 23 
Area_max : 198 
Width_min : 23 
Width_max : 198 
green_filter : False 
camera_start_height : 337 
camera_bottom_height : 637 
camera_left_width : 39 
camera_right_width : 760 
