Hue_low : 89 
Hue_high : 106 
Saturation_low : 47 
Saturation_high : 255 
Value_low : 129 
Value_high : 255 
Area_min : 14 
Area_max : 500 
Width_min : 14 
Width_max : 500 
green_filter : False 
camera_start_height : 300 
camera_bottom_height : 600 
camera_left_width : 0 
camera_right_width : 800 
