Hue_low : 0
Hue_high : 80
Saturation_low : 30
Saturation_high : 255
Value_low : 200
Value_high : 255
Width_min : 10
Width_max : 50
Area_min : 56 
Area_max : 240 
Width_min : 56 
Width_max : 240 
green_filter : False 
camera_start_height : 258 
camera_bottom_height : 630 
camera_left_width : 0 
camera_right_width : 800 